services:
  backend:
    build: .
    container_name: ecolearn-backend
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      - MONGO_URI=mongodb://db:27017/ecolearn
    depends_on:
      - db
    networks:
      - ecolearn-network

  db:
    image: mongo:4.4
    container_name: ecolearn-db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - ecolearn-network

volumes:
  mongodb_data:

networks:
  ecolearn-network:
    driver: bridge
