services:
  backend:
    build: .
    container_name: ecolearn-backend
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - ./src/uploads:/app/src/uploads
    networks:
      - ecolearn-network

networks:
  ecolearn-network:
    driver: bridge
